name: Build and Run DiscordAuth

on:
  push:
    branches:
      - main  # Dies sorgt dafür, dass der Workflow bei jedem Push auf den "main"-Branch ausgeführt wird.

jobs:
  build:
    runs-on: windows-latest  # Setzt das Betriebssystem, auf dem der Code ausgeführt wird.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Holt den Code aus deinem Repository

      - name: Set up .NET
        uses: actions/setup-dotnet@v2  # Setzt die .NET-Version
        with:
          dotnet-version: '6.0'  # Hier kannst du die .NET-Version anpassen, die du verwendest

      - name: Build with .NET
        run: dotnet build  # Baut das Projekt

      - name: Run the application with GitHub secrets
        run: |
          dotnet run --clientSecret ${{ secrets.DISCORD_CLIENT_SECRET }} --allowedUsers ${{ secrets.DISCORD_ALLOWED_USERS }}
